const { test, expect } = require('@playwright/test');
const path = require('path');
const { openApp, PROFILE } = require('./helpers');

// The import pipeline is the most destructive code in the app — it rewrites or merges a user's
// whole workspace — and had no coverage at all. These run the real path: a real .xlsx through the
// real file input, the real detector, the real commit.
//
// Fixtures are generated by tests/fixtures/make-workbooks.js from the genuine ScheduleHub v3.1
// starter template, so their sheet names and column headers are the ones the detectors key off
// rather than a guess at them.
const WORKBOOKS = path.join(__dirname, 'fixtures', 'workbooks');
const generated = (name) => path.join(WORKBOOKS, 'generated', name);

const NATIVE_OVERLAY = '#nsNativeImport';

async function openFresh(page) {
  await openApp(page, { profile: PROFILE, workspaceRow: null });
  await page.waitForFunction(() => !!document.getElementById('fi') && typeof XLSX === 'object');
  // The import path refuses to start until the bundled parser reports ready.
  await page.waitForFunction(() => {
    try { return requireExcelParserReady(); } catch (e) { return false; }
  }, null, { timeout: 30_000 });
}

async function uploadWorkbook(page, file) {
  await page.setInputFiles('#fi', file);
}

test.describe('native SyncSheets import', () => {
  test('a ScheduleHub workbook is detected and previewed before anything is committed', async ({ page }) => {
    await openFresh(page);
    await uploadWorkbook(page, generated('schedulehub-two-teams.xlsx'));

    const overlay = page.locator(NATIVE_OVERLAY);
    await expect(overlay).toBeVisible({ timeout: 40_000 });
    await expect(overlay).toContainText('ScheduleHub detected');
    await expect(overlay).toContainText('168');

    // Nothing has been written yet — the preview is a preview.
    expect(await page.evaluate(() => S.entries.length)).toBe(0);
    expect(await page.evaluate(() => nsListCanonicalProjects().length)).toBe(0);
  });

  test('confirming the import commits the rows and opens the workspace', async ({ page }) => {
    await openFresh(page);
    await uploadWorkbook(page, generated('schedulehub-two-teams.xlsx'));
    await expect(page.locator(NATIVE_OVERLAY)).toBeVisible({ timeout: 40_000 });

    await page.locator(`${NATIVE_OVERLAY} button.primary`).click();
    await expect(page.locator(NATIVE_OVERLAY)).toHaveCount(0);

    await expect.poll(() => page.evaluate(() => nsListCanonicalProjects().length), { timeout: 30_000 }).toBeGreaterThan(0);
    const projects = await page.evaluate(() => nsListCanonicalProjects().map((p) => ({ name: p.name, schedule: p.scheduleCount })));
    expect(projects[0].schedule).toBe(168);
    await expect(page.locator('#mv')).toBeVisible();
  });

  test('cancelling leaves the workspace untouched', async ({ page }) => {
    await openFresh(page);
    await uploadWorkbook(page, generated('schedulehub-two-teams.xlsx'));
    await expect(page.locator(NATIVE_OVERLAY)).toBeVisible({ timeout: 40_000 });

    await page.locator(NATIVE_OVERLAY).getByRole('button', { name: 'Cancel' }).click();
    await expect(page.locator(NATIVE_OVERLAY)).toHaveCount(0);
    expect(await page.evaluate(() => nsListCanonicalProjects().length)).toBe(0);
    expect(await page.evaluate(() => S.entries.length)).toBe(0);
    // Still on the landing screen, with the import route intact.
    await expect(page.locator('#mv')).toBeHidden();
  });

  test('an empty starter template is refused with an explanation, not a silent no-op', async ({ page }) => {
    // The blank v3.1 template has the right shape but no rows. It must not import as an empty
    // project, and it must not fail invisibly either.
    await openFresh(page);
    await uploadWorkbook(page, path.join(WORKBOOKS, 'ScheduleHub_v3.1_Starter.xlsx'));

    const overlay = page.locator(NATIVE_OVERLAY);
    await expect(overlay).toBeVisible({ timeout: 40_000 });
    await expect(overlay).toContainText('0');

    await page.locator(`${NATIVE_OVERLAY} button.primary`).click();
    await expect(overlay).toHaveCount(0);
    // Nothing real was created from an empty template.
    const projects = await page.evaluate(() => nsListCanonicalProjects());
    expect(projects).toEqual([]);
  });

  test('a workbook with a repeated row still imports, and reports what it saw', async ({ page }) => {
    await openFresh(page);
    await uploadWorkbook(page, generated('schedulehub-duplicate-rows.xlsx'));
    const overlay = page.locator(NATIVE_OVERLAY);
    await expect(overlay).toBeVisible({ timeout: 40_000 });
    // 42 real rows plus the one exact duplicate.
    await expect(overlay).toContainText('43');

    await page.locator(`${NATIVE_OVERLAY} button.primary`).click();
    await expect.poll(() => page.evaluate(() => nsListCanonicalProjects().length), { timeout: 30_000 }).toBeGreaterThan(0);
    // Merging is by stable ID, so the duplicate must not double-count.
    const schedule = await page.evaluate(() => nsListCanonicalProjects()[0].scheduleCount);
    expect(schedule).toBeLessThanOrEqual(43);
  });

  test('re-importing the identical workbook is refused rather than duplicated', async ({ page }) => {
    await openFresh(page);
    await uploadWorkbook(page, generated('schedulehub-two-teams.xlsx'));
    await expect(page.locator(NATIVE_OVERLAY)).toBeVisible({ timeout: 40_000 });
    await page.locator(`${NATIVE_OVERLAY} button.primary`).click();
    await expect.poll(() => page.evaluate(() => nsListCanonicalProjects().length), { timeout: 30_000 }).toBeGreaterThan(0);
    const before = await page.evaluate(() => nsListCanonicalProjects()[0].scheduleCount);

    await uploadWorkbook(page, generated('schedulehub-two-teams.xlsx'));
    await page.waitForTimeout(6000);
    const after = await page.evaluate(() => nsListCanonicalProjects()[0].scheduleCount);
    expect(after).toBe(before);
  });
});

test.describe('import safety net', () => {
  test('a native import takes a restore point before it commits', async ({ page }) => {
    // Regression: the snapshot hook was originally added only to confirmParsePreview, which handles
    // general-roster workbooks. Every native SyncSheets format commits through
    // nsConfirmNativeImport instead, so the formats this product is built around were importing
    // with no way back.
    await openFresh(page);
    await uploadWorkbook(page, generated('schedulehub-two-teams.xlsx'));
    await expect(page.locator(NATIVE_OVERLAY)).toBeVisible({ timeout: 40_000 });
    await page.locator(`${NATIVE_OVERLAY} button.primary`).click();
    await expect.poll(() => page.evaluate(() => nsListCanonicalProjects().length), { timeout: 30_000 }).toBeGreaterThan(0);

    // nsConfirmNativeImport deliberately does not await the snapshot: its IndexedDB write settles
    // after the commit, and the index entry is only written once that put completes. Reading the
    // index the moment the projects appear races that write under load.
    await expect
      .poll(() => page.evaluate(() => nsListSnapshots().some((s) => s.reason === 'auto-import')), { timeout: 30_000 })
      .toBe(true);
  });

  test('the restore point holds the workspace as it was BEFORE the import', async ({ page }) => {
    // A snapshot taken after the merge would be worthless. Import once, then import a second
    // workbook and confirm the newest restore point still describes the first world.
    await openFresh(page);
    await uploadWorkbook(page, generated('schedulehub-two-teams.xlsx'));
    await expect(page.locator(NATIVE_OVERLAY)).toBeVisible({ timeout: 40_000 });
    await page.locator(`${NATIVE_OVERLAY} button.primary`).click();
    await expect.poll(() => page.evaluate(() => nsListCanonicalProjects().length), { timeout: 30_000 }).toBeGreaterThan(0);
    const afterFirst = await page.evaluate(() => nsListCanonicalProjects()[0].scheduleCount);

    await uploadWorkbook(page, generated('schedulehub-same-name-later-month.xlsx'));
    await expect(page.locator(NATIVE_OVERLAY)).toBeVisible({ timeout: 40_000 });
    await page.locator(`${NATIVE_OVERLAY} button.primary`).click();
    await expect
      .poll(() => page.evaluate(() => nsListSnapshots().filter((s) => s.reason === 'auto-import').length), { timeout: 30_000 })
      .toBeGreaterThanOrEqual(2);

    const newest = await page.evaluate(() => nsListSnapshots().filter((s) => s.reason === 'auto-import')[0]);
    expect(newest.schedule).toBe(afterFirst);
  });

  test('restoring undoes an import', async ({ page }) => {
    await openFresh(page);
    await uploadWorkbook(page, generated('schedulehub-two-teams.xlsx'));
    await expect(page.locator(NATIVE_OVERLAY)).toBeVisible({ timeout: 40_000 });
    await page.locator(`${NATIVE_OVERLAY} button.primary`).click();
    await expect.poll(() => page.evaluate(() => nsListCanonicalProjects().length), { timeout: 30_000 }).toBeGreaterThan(0);

    // Wait for the restore point to land (see the first test in this block for why it is async).
    await expect
      .poll(() => page.evaluate(() => nsListSnapshots().some((s) => s.reason === 'auto-import')), { timeout: 30_000 })
      .toBe(true);
    const id = await page.evaluate(() => nsListSnapshots().find((s) => s.reason === 'auto-import').id);
    const result = await page.evaluate((snapId) => nsRestoreSnapshot(snapId), id);
    expect(result.ok).toBe(true);
    // Back to an empty workspace, which is what it was before the import.
    expect(await page.evaluate(() => nsListCanonicalProjects().length)).toBe(0);
  });
});
