const TH={
  surge:     {n:"Surge",     dark:true,  cls:"",            d:"#5a8ab0", desc:"Cool neutral — 7OS default"},
  tide:      {n:"Tide",      dark:true,  cls:"th-tide",     d:"#4db8c8", desc:"Teal-graphite — clinical"},
  press:     {n:"Press",     dark:false, cls:"th-press",    d:"#6B4C2A", desc:"Warm editorial light"},
  newsprint: {n:"Newsprint", dark:false, cls:"th-newsprint",d:"#9381FF", desc:"Cool editorial light"}
};
/* ── v60: Multi-variant theme system — 4 themes × 25 variants ── */
const THEME_VARIANTS={
  surge:["violet-core","electric-arc","hot-fuchsia","tropical-mint","berry-bloom","chartreuse","cobalt-surge","acid-lime","nightshade","crimson-wire","plasma-blue","void-teal","neon-orange","deep-amber","retro-coral","steel-mauve","cold-lavender","gunmetal-violet","slate-surge","ultraviolet","cotton-candy","disco-silver","rose-neon","solar-flare","midnight-rose"],
  tide:["teal-core","regal-navy","forest-pine","sandelwood","citrus-strike","iron-teal","petroleum","deep-slate","obsidian-tide","storm-grey","copper-tide","rust-teal","kelp-stone","onyx-mint","charcoal-sage","ash-steel","graphite-zero","denim","military-olive","battleship","seafoam-day","ice-sheet","stone-wash","pewter-sage","patina","nordic-frost"],
  press:["almond-core","petal-rose","powder-blush","linen-turf","citrus-press","lavender-mist","terracotta","marigold","dusty-lilac","fig-cream","coral-dusk","saffron-ink","mallow-pink","peach-fizz","warm-ivory","blush-slate","sage-rose","dried-petal","champagne","pressed-flower","blossom-print","parchment","nude-copper","porcelain","alabaster"],
  newsprint:["chiffon-core","powder-star","blueprint","tidal-green","graphite-np","rye-ink","army-drab","denim-wash","slate-moss","steel-cedar","storm-indigo","fog-fern","rain-rust","urban-pewter","khaki-bone","nordic-pine","spruce","harbour-grey","loden","oxford","sage-parchment","ink-wheat","brunswick","cartographer","moonprint"],
};
/* ── Dynamic card surface palettes (cycled by variant index) ── */
const THEME_CARD_PALETTES={
  surge:[
    {card:'rgba(20,28,42,.82)',border:'rgba(90,138,176,.14)',top:'rgba(90,138,176,.08)'},
    {card:'rgba(42,30,74,.84)',border:'rgba(128,108,233,.16)',top:'rgba(128,108,233,.07)'},
    {card:'rgba(27,24,66,.85)',border:'rgba(89,64,155,.18)',top:'rgba(126,108,206,.06)'},
    {card:'rgba(36,22,64,.84)',border:'rgba(141,43,144,.17)',top:'rgba(141,43,144,.06)'},
  ],
  tide:[
    {card:'rgba(30,38,43,.86)',border:'rgba(77,184,200,.15)',top:'rgba(77,184,200,.07)'},
    {card:'rgba(26,44,50,.84)',border:'rgba(74,120,176,.16)',top:'rgba(74,120,176,.07)'},
    {card:'rgba(36,40,40,.84)',border:'rgba(109,159,113,.15)',top:'rgba(109,159,113,.06)'},
    {card:'rgba(28,34,38,.86)',border:'rgba(110,154,176,.15)',top:'rgba(110,154,176,.06)'},
  ],
  press:[
    {card:'rgba(235,211,187,.92)',border:'rgba(107,76,42,.16)',top:'rgba(107,76,42,.07)'},
    {card:'rgba(240,222,200,.92)',border:'rgba(159,126,94,.16)',top:'rgba(159,126,94,.07)'},
    {card:'rgba(246,232,214,.93)',border:'rgba(138,96,96,.15)',top:'rgba(138,96,96,.06)'},
    {card:'rgba(233,219,202,.92)',border:'rgba(124,92,138,.15)',top:'rgba(124,92,138,.06)'},
  ],
  newsprint:[
    {card:'rgba(250,240,202,.92)',border:'rgba(147,129,255,.15)',top:'rgba(147,129,255,.07)'},
    {card:'rgba(244,236,210,.93)',border:'rgba(13,59,102,.15)',top:'rgba(13,59,102,.06)'},
    {card:'rgba(240,244,232,.93)',border:'rgba(77,124,111,.14)',top:'rgba(77,124,111,.05)'},
    {card:'rgba(238,240,248,.93)',border:'rgba(90,96,128,.14)',top:'rgba(90,96,128,.05)'},
  ],
};
/* ── v60: Variant labels for settings picker ── */
const THEME_VARIANTS_LABELS={
  surge:{
    "violet-core":{l:"7OS Core",c:"dark"},
    "electric-arc":{l:"Electric Arc",c:"dark"},
    "hot-fuchsia":{l:"Hot Fuchsia",c:"dark"},
    "tropical-mint":{l:"Tropical Mint",c:"dark"},
    "berry-bloom":{l:"Berry Bloom",c:"dark"},
    "chartreuse":{l:"Chartreuse",c:"dark"},
    "cobalt-surge":{l:"Cobalt Surge",c:"dark"},
    "acid-lime":{l:"Acid Lime",c:"dark"},
    "nightshade":{l:"Nightshade",c:"dark"},
    "crimson-wire":{l:"Crimson Wire",c:"dark"},
    "plasma-blue":{l:"Plasma Blue",c:"mid"},
    "void-teal":{l:"Void Teal",c:"mid"},
    "neon-orange":{l:"Neon Orange",c:"mid"},
    "deep-amber":{l:"Deep Amber",c:"mid"},
    "retro-coral":{l:"Retro Coral",c:"mid"},
    "steel-mauve":{l:"Steel Mauve",c:"neutral"},
    "cold-lavender":{l:"Cold Lavender",c:"neutral"},
    "gunmetal-violet":{l:"Gunmetal Violet",c:"neutral"},
    "slate-surge":{l:"Slate Surge",c:"neutral"},
    "ultraviolet":{l:"Ultraviolet",c:"light"},
    "cotton-candy":{l:"Cotton Candy",c:"light"},
    "disco-silver":{l:"Disco Silver",c:"light"},
    "rose-neon":{l:"Rose Neon",c:"light"},
    "solar-flare":{l:"Solar Flare",c:"light"},
    "midnight-rose":{l:"Midnight Rose",c:"light"},
  },
  tide:{
    "teal-core":{l:"Teal Core",c:"dark"},
    "regal-navy":{l:"Regal Navy",c:"dark"},
    "forest-pine":{l:"Forest Pine",c:"dark"},
    "sandelwood":{l:"Sandelwood",c:"dark"},
    "citrus-strike":{l:"Citrus Strike",c:"dark"},
    "iron-teal":{l:"Iron Teal",c:"dark"},
    "petroleum":{l:"Petroleum",c:"dark"},
    "deep-slate":{l:"Deep Slate",c:"dark"},
    "obsidian-tide":{l:"Obsidian Tide",c:"dark"},
    "storm-grey":{l:"Storm Grey",c:"dark"},
    "copper-tide":{l:"Copper Tide",c:"mid"},
    "rust-teal":{l:"Rust & Teal",c:"mid"},
    "kelp-stone":{l:"Kelp & Stone",c:"mid"},
    "onyx-mint":{l:"Onyx & Mint",c:"mid"},
    "charcoal-sage":{l:"Charcoal Sage",c:"mid"},
    "ash-steel":{l:"Ash & Steel",c:"neutral"},
    "graphite-zero":{l:"Graphite Zero",c:"neutral"},
    "denim":{l:"Denim",c:"neutral"},
    "military-olive":{l:"Military Olive",c:"neutral"},
    "battleship":{l:"Battleship",c:"neutral"},
    "seafoam-day":{l:"Seafoam Day",c:"light"},
    "ice-sheet":{l:"Ice Sheet",c:"light"},
    "stone-wash":{l:"Stone Wash",c:"light"},
    "pewter-sage":{l:"Pewter & Sage",c:"light"},
    "patina":{l:"Patina",c:"light"},
    "nordic-frost":{l:"Nordic Frost",c:"light"},
  },
  press:{
    "almond-core":{l:"Almond Core",c:"light"},
    "petal-rose":{l:"Petal Rose",c:"light"},
    "powder-blush":{l:"Powder Blush",c:"light"},
    "linen-turf":{l:"Linen & Turf",c:"light"},
    "citrus-press":{l:"Citrus Press",c:"light"},
    "lavender-mist":{l:"Lavender Mist",c:"light"},
    "terracotta":{l:"Terracotta",c:"light"},
    "marigold":{l:"Marigold",c:"light"},
    "dusty-lilac":{l:"Dusty Lilac",c:"light"},
    "fig-cream":{l:"Fig & Cream",c:"light"},
    "coral-dusk":{l:"Coral Dusk",c:"light"},
    "saffron-ink":{l:"Saffron & Ink",c:"light"},
    "mallow-pink":{l:"Mallow Pink",c:"light"},
    "peach-fizz":{l:"Peach Fizz",c:"light"},
    "warm-ivory":{l:"Warm Ivory",c:"light"},
    "blush-slate":{l:"Blush & Slate",c:"mid"},
    "sage-rose":{l:"Sage & Rose",c:"mid"},
    "dried-petal":{l:"Dried Petal",c:"mid"},
    "champagne":{l:"Champagne",c:"mid"},
    "pressed-flower":{l:"Pressed Flower",c:"mid"},
    "blossom-print":{l:"Blossom Print",c:"neutral"},
    "parchment":{l:"Parchment",c:"neutral"},
    "nude-copper":{l:"Nude & Copper",c:"neutral"},
    "porcelain":{l:"Porcelain",c:"neutral"},
    "alabaster":{l:"Alabaster",c:"neutral"},
  },
  newsprint:{
    "chiffon-core":{l:"Chiffon Core",c:"light"},
    "powder-star":{l:"Powder Star",c:"light"},
    "blueprint":{l:"Blueprint",c:"light"},
    "tidal-green":{l:"Tidal Green",c:"light"},
    "graphite-np":{l:"Graphite",c:"light"},
    "rye-ink":{l:"Rye & Ink",c:"light"},
    "army-drab":{l:"Army Drab",c:"light"},
    "denim-wash":{l:"Denim Wash",c:"light"},
    "slate-moss":{l:"Slate & Moss",c:"light"},
    "steel-cedar":{l:"Steel & Cedar",c:"light"},
    "storm-indigo":{l:"Storm Indigo",c:"mid"},
    "fog-fern":{l:"Fog & Fern",c:"mid"},
    "rain-rust":{l:"Rain & Rust",c:"mid"},
    "urban-pewter":{l:"Urban Pewter",c:"mid"},
    "khaki-bone":{l:"Khaki & Bone",c:"mid"},
    "nordic-pine":{l:"Nordic Pine",c:"neutral"},
    "spruce":{l:"Spruce",c:"neutral"},
    "harbour-grey":{l:"Harbour Grey",c:"neutral"},
    "loden":{l:"Loden",c:"neutral"},
    "oxford":{l:"Oxford",c:"neutral"},
    "sage-parchment":{l:"Sage Parchment",c:"neutral"},
    "ink-wheat":{l:"Ink & Wheat",c:"neutral"},
    "brunswick":{l:"Brunswick",c:"neutral"},
    "cartographer":{l:"Cartographer",c:"neutral"},
    "moonprint":{l:"Moonprint",c:"neutral"},
  },
};